MODEL:
  META_ARCHITECTURE: "OneNet"
  WEIGHTS: "Weights/mobilenet_v3_small.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_mobilenetV3small_fpn_backbone"
    FREEZE_AT: 0

  RESNETS:
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]

  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]

  OneNet:
    #DCN: False
    NUM_CLASSES: 2
    #DECONV_CHANNEL: (960, 112, 40, 24)

    HEAD: "FCOS"
    #DIOU_COST: 2.0
    #IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    IN_FEATURES: ["p3", "p4", "p5"]
    #IN_FEATURES: ["p3", "p4", "p5", "p6"]

SOLVER:
  IMS_PER_BATCH: 16 #8 #64 bachsize最大在这台服务器上是16
  BASE_LR: 0.00005 1
  STEPS: (62240, 74080)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 10000

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0  # keep same with BASE_LR.
  CLIP_GRADIENTS:
    ENABLED: False
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
SEED: 40244023
INPUT:
  MIN_SIZE_TRAIN: (416, 448, 480, 512)
  MAX_SIZE_TRAIN: 853
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 853
  CROP:
    ENABLED: True 
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 0
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)

OUTPUT_DIR: 'build_mobilenetV3large_fpn_backbone'
